name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Poetry
        run: pipx install poetry==2.4.1
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with=dev --no-interaction --no-root
      - name: Lint
        run: poetry run pycodestyle
      - name: Test and check coverage
        run: poetry run pytest --cov=offload --cov-report=term --cov-fail-under=80

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
